# Workflow sets up the ECR Repository, Permissions and Lambda function for a newly created repo (from template)
name: AWS Lambda Function Initialisation

on:
  # Trigger when the repo is created
  create:

  # For testing, allow the workflow to be triggered manually
  workflow_dispatch:

jobs:
  # Initialise resources on AWS
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(secrets) }}
        run: echo "$GITHUB_CONTEXT"
      # Setup AWS Credentials (will be detected and used by the following calls to the AWS CLI)
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-west-2
